### ISSUE TITLE
Slight update to documentation

### ISSUE THREAD

**Issue by pmeaney** [Zi0P4tch0/RadioGoGo#4]
Hi there,

I'd like to add one item to the install documentation for MacOS.

For MacOS, after installing Go, Go needs to be added to $PATH:

**Please add this to the tutorial:**
`export PATH=$PATH:$(go env GOPATH)/bin`

**MacOS Install TLDR:**

```bash
brew install ffmpeg
brew install go
# Append Go to $PATH so Golang applications' commands can be found by system. 
export PATH=$PATH:$(go env GOPATH)/bin
go install github.com/zi0p4tch0/radiogogo@latest
radiogogo
```

_____________________
(Initially, On MacOS, from my terminal I ran these, but ran into the error listed below)

```bash
brew install ffmpeg
brew install go
go install github.com/zi0p4tch0/radiogogo@latest
radiogogo
--> "zsh: command not found: radiogogo"
```

**Comment by Zi0P4tch0** [comment]
Fixed in 69f59d4b2949f069e4f3a89ad904097bcd4eb8c7 , and thanks for the feedback!
